os:
  - linux
  - osx

matrix:
    allow_failures:
        - os: osx

dist: trusty
sudo: required

language: cpp

compiler:
  - gcc
  - clang

env:
  matrix:
    - DEBUG_OPT=""
    - DEBUG_OPT="--enable-optimized-debug"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then source .travis/install-osx.sh; fi

addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libx11-dev
      - zlib1g-dev
      - libgl1-mesa-dev
      - libogg-dev
      - libvorbis-dev
      - libasound2-dev
      - libfluidsynth-dev
      - libsdl-ttf2.0-dev
      - libpng-dev
      - libfreetype6-dev
      - libglade2-dev
      - libgtk2.0-dev
      - libpango1.0-dev
      - libatk1.0-dev
      - libcairo2-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxml2-dev
      - bison
      - flex
      - libgnomeui-dev
      - timidity
      - libgimp2.0-dev

script: .travis/script.sh

notifications:
    email: false
    irc: "chat.freenode.net/#exult"
    on_success: change
    on_failure: always

