name: ci-macos

on: [push, pull_request]

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install sdl2 --head
          brew install automake libtool pkg-config libpng zlib libogg libvorbis freetype gtk+3 libxml2 bison flex
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run autogen
        run: |
          chmod a+x ./autogen.sh
          ./autogen.sh
      - name: Configure
        run: |
          ./configure --with-debug=extreme --enable-exult-studio --enable-exult-studio-support --enable-compiler \
            --enable-zip-support --enable-shared --enable-gnome-shp-thumbnailer --enable-data --enable-mods \
            --disable-alsa --disable-fluidsynth --disable-timidity-midi --disable-oggtest --disable-vorbistest
      - name: Build
        run: |
          make -j2
