name: ci-macos

on:
  push:
    paths:
      - '!docs/**'
      - 'docs/Makefile.am'
      - '!msvcstuff/**'
      - '!win32/**'
      - '!AUTHORS'
      - '!ChangeLog'
      - '!COPYING'
      - '!FAQ'
      - '!INSTALL'
      - '!NEWS'
      - '!**README**'
      - '!**.ico'
      - '!**.md'
      - '!**.png'
      - '!**.txt'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'
  pull_request:
    paths:
      - '!docs/**'
      - 'docs/Makefile.am'
      - '!msvcstuff/**'
      - '!win32/**'
      - '!AUTHORS'
      - '!ChangeLog'
      - '!COPYING'
      - '!FAQ'
      - '!INSTALL'
      - '!NEWS'
      - '!**README**'
      - '!**.ico'
      - '!**.md'
      - '!**.png'
      - '!**.txt'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install automake hg libtool pkg-config libpng zlib libogg libvorbis freetype gtk+3 libxml2 bison flex
          brew install sdl2 --head
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run autogen
        run: |
          chmod a+x ./autogen.sh
          ./autogen.sh
      - name: Configure
        run: |
          export LDFLAGS="-L$(brew --prefix bison)/lib -L$(brew --prefix flex)/lib -L$(brew --prefix zlib)/lib"
          export CPPFLAGS="-I$(brew --prefix flex)/include -I$(brew --prefix zlib)/include"
          export PATH="$(brew --prefix bison)/bin:$(brew --prefix flex)/bin:$(brew --prefix libxml2)/bin:$PATH"
          export PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix libxml2)/lib/pkgconfig"
          ./configure --with-debug=extreme --enable-exult-studio --enable-exult-studio-support --enable-compiler \
            --enable-zip-support --enable-shared --enable-gnome-shp-thumbnailer --enable-data --enable-mods \
            --disable-alsa --disable-fluidsynth --disable-timidity-midi --disable-oggtest --disable-vorbistest
      - name: Build
        run: |
          export LDFLAGS="-L$(brew --prefix bison)/lib -L$(brew --prefix flex)/lib -L$(brew --prefix zlib)/lib"
          export CPPFLAGS="-I$(brew --prefix flex)/include -I$(brew --prefix zlib)/include"
          export PATH="$(brew --prefix bison)/bin:$(brew --prefix flex)/bin:$(brew --prefix libxml2)/bin:$PATH"
          export PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix libxml2)/lib/pkgconfig"
          make -j2
