name: ci-windows

on:
  push:
    paths:
      - '**'
      - '!docs/**'
      - 'docs/Makefile.am'
      - '!ios/**'
      - '!macos/**'
      - '!msvcstuff/**'
      - '!AUTHORS'
      - '!ChangeLog'
      - '!COPYING'
      - '!FAQ'
      - '!INSTALL'
      - '!NEWS'
      - '!**README**'
      - '!**.ico'
      - '!**.md'
      - '!**.png'
      - '!**.txt'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-windows.yml'
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - 'docs/Makefile.am'
      - '!ios/**'
      - '!macos/**'
      - '!msvcstuff/**'
      - '!AUTHORS'
      - '!ChangeLog'
      - '!COPYING'
      - '!FAQ'
      - '!INSTALL'
      - '!NEWS'
      - '!**README**'
      - '!**.ico'
      - '!**.md'
      - '!**.png'
      - '!**.txt'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-windows.yml'

jobs:
  ci-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install:
            base-devel git mingw-w64-x86_64-toolchain mingw-w64-x86_64-binutils mingw-w64-x86_64-ntldd mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-fluidsynth mingw-w64-x86_64-libogg mingw-w64-x86_64-libvorbis mingw-w64-x86_64-munt-mt32emu
            mingw-w64-x86_64-zlib mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-gtk3 mingw-w64-x86_64-adwaita-icon-theme
            mingw-w64-x86_64-libxml2 mingw-w64-x86_64-freetype mingw-w64-x86_64-gtk2 mingw-w64-x86_64-gimp
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: |
          make -j2 -f Makefile.mingw DEBUG=1 USECODE_CONTAINER=1 USECODE_DEBUGGER=1 SHOW_NONREADIED_OBJECTS=1 Exult.exe exult_studio.exe tools u7shp.exe
